### ISSUE TITLE
Missing parenthesis in example

### ISSUE THREAD

**Issue by Nicolazinho** [BeepBoopHQ/beepboop-js#9]
The [event close](https://github.com/BeepBoopHQ/beepboop-js#event-close) example is missing the closing parenthesis

**Comment by selfcontained** [comment]
For the life of me I can't find the missing parenthesis you mentioned, I'm sure I'm overlooking it though.  Feel free to open a PR fixing it, or if you can show exactly what you mean that would help, as I can't seem to find it 😄

**Comment by Nicolazinho** [comment]
Added a new [PR #10](https://github.com/BeepBoopHQ/beepboop-js/pull/10).

**Comment by Nicolazinho** [comment]
Resolved in [PR 10](https://github.com/BeepBoopHQ/beepboop-js/pull/10)
